# Overall filter parameters
base_frame_id:    robot_footprint
global_frame_id:  map
min_particles:    10
max_particles:    200 
initial_pose_x:   0.0
initial_pose_y:   0.0
initial_pose_a:   0.0

# Laser model parameters
laser_model_type: likelihood_field
laser_z_hit:      0.95 #default
laser_z_rand:     0.05 #default
laser_max_beams:  30 #default

# Odometry model parameters
odom_frame_id:    odom
odom_model_type:  diff-corrected
odom_alpha1:      0.01 #0.2
odom_alpha2:      0.01 #0.2
odom_alpha3:      0.01 #0.2
odom_alpha4:      0.01 #0.2

