global_costmap:
   global_frame:      map
   robot_base_frame:  robot_footprint
   update_frequency:  15.0 #10.0
   publish_frequency: 15.0 #10.0
   width:             20.0 #50.0
   height:            20.0 #50.0
   resolution:        0.05 #0.02
   static_map:        true
   rolling_window:    false
