local_costmap:
   global_frame:      odom
   robot_base_frame:  robot_footprint
   update_frequency:  15.0 #10.0
   publish_frequency: 15.0 #10.0
   width:             5.0 #4.0
   height:            5.0 #4.0
   resolution:        0.05 #0.02
   static_map:        false
   rolling_window:    true 
