map_type: costmap

obstacle_range: 3.0
raytrace_range: 3.0

transform_tolerance: 0.3

robot_radius: 0.35 
inflation_radius: 0.6

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /safa_bot/laser/scan, marking: true, clearing: true}
